// See https://aka.ms/new-console-template for more information
Console.WriteLine("                 EasyDevOps");
Console.WriteLine("               .+@-...  . .-@=                ");
Console.WriteLine("           .@                    @.           ");
Console.WriteLine("         %                          @         ");
Console.WriteLine("      .-                              *       ");
Console.WriteLine("     %                                  @     ");
Console.WriteLine("   .                                     ..   ");
Console.WriteLine("  =                                       ..  ");
Console.WriteLine(" ..                                        .. ");
Console.WriteLine(" = ####. -#############..######.   *#####=  # ");
Console.WriteLine("+ .****. -*************..******#  .******-   .");
Console.WriteLine("% .****.     .****+.... .***#***. ***#***-   %");
Console.WriteLine("= .****.     .****+ ..  .***#***#.#*##***-   %");
Console.WriteLine("+ .****.      ****+     .***#.******.#***-   %");
Console.WriteLine("% .****.      ****+.    .***#.*****# ****-   @");
Console.WriteLine("= .****.     .****+..   .***#..****. ****-   .");
Console.WriteLine(".=.++++.      ****=     .***+  *+++. ++++-. %.");
Console.WriteLine(" ..                                        .. ");
Console.WriteLine("  -                                       ..  ");
Console.WriteLine("   ..                                    :.   ");
Console.WriteLine("     %                                  @     ");
Console.WriteLine("      .+                              %.      ");
Console.WriteLine("        .@                         .@         ");
Console.WriteLine("           .@                   .@            ");
Console.WriteLine("               .-@*..    ..#@:                ");
Console.WriteLine("");
Console.WriteLine("                  EasyDevOps");
